SELECT 
  UTILISATEUR.nom, 
  UTILISATEUR.prenom,
  UTILISATEUR.age 
FROM 
  COMPETITEUR, UTILISATEUR,PARTICIPE_COMPETITEUR 
  WHERE COMPETITEUR.numCompetiteur = PARTICIPE_COMPETITEUR.numCompetiteur 
  AND   COMPETITEUR.numCompetiteur=UTILISATEUR.numUtilisateur
  GROUP BY COMPETITEUR.numCompetiteur
HAVING 
  (SELECT COUNT(*) FROM PARTICIPE_COMPETITEUR WHERE PARTICIPE_COMPETITEUR.numCompetiteur=COMPETITEUR.numCompetiteur) = (SELECT COUNT(*) FROM CONCOURS)
