SELECT 
  DESSIN.numDessin, 
  EVALUATION.note, 
  UTILISATEUR.nom,
  UTILISATEUR.prenom,
  CONCOURS.descriptif,
  CONCOURS.theme
FROM 
  DESSIN,EVALUATION, COMPETITEUR, PARTICIPE_COMPETITEUR,CONCOURS, UTILISATEUR
WHERE 
  YEAR(EVALUATION.dateEvaluation) = 2022 
  AND DESSIN.numDessin = EVALUATION.numDessin 
  AND DESSIN.numCompetiteur = COMPETITEUR.numCompetiteur
  AND DESSIN.numCompetiteur = PARTICIPE_COMPETITEUR.numCompetiteur 
  AND PARTICIPE_COMPETITEUR.numConcours = CONCOURS.numConcours
  AND COMPETITEUR.numCompetiteur=UTILISATEUR.numUtilisateur
ORDER BY EVALUATION.note ASC;