-- Concours 1
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('In quis justo.', '2022-08-20', 'Red Shoes, The (Bunhongsin)', 1, 32);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Sed vel enim sit amet nunc viverra dapibus.', '2022-02-08', 'Full of It', 1, 23);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Nulla justo.', '2022-06-17', 'Belle', 1, 30);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Vestibulum sed magna at nunc commodo placerat.', '2022-02-02', 'Five Graves to Cairo', 1, 21);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('In congue.', '2022-04-27', 'Paradox', 1, 29);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Vestibulum ac est lacinia nisi venenatis tristique.', '2022-02-19', 'Watch the Birdie', 1, 30);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('In blandit ultrices enim.', '2022-12-15', 'Beau Pere (a.k.a. Stepfather) (Beau-père)', 1, 25);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', '2022-02-14', 'Jakob the Liar', 1, 24);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Nulla tempus.', '2022-03-31', 'Fish Child, The (El niño pez)', 1, 32);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', '2022-02-07', 'My Big Fat Greek Wedding', 1, 25);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2022-02-26', 'Sexy Nights of the Living Dead', 1, 24);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Curabitur convallis.', '2022-05-25', 'Twixt', 1, 23);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Duis bibendum.', '2022-12-09', 'Straw Dogs', 1, 29);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '2022-02-03', 'Diary of a Chambermaid, The', 1, 28);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Nulla mollis molestie lorem.', '2022-02-27', 'Why Worry?', 1, 28);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Pellentesque viverra pede ac diam.', '2022-02-27', 'Incir Reçeli', 1, 31);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Aenean sit amet justo.', '2022-02-02', 'Alex Cross', 1, 31);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Integer tincidunt ante vel ipsum.', '2022-02-07', 'Poor Boy''s Game', 1, 27);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Duis bibendum.', '2022-02-10', 'Shark Night 3D', 1, 34);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', '2022-02-02', 'Lady of Chance, A', 1, 33);
-- Concours 2
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Morbi vel lectus in quam fringilla rhoncus.', '2021-05-02', 'Grave Encounters', 2, 42);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Integer tincidunt ante vel ipsum.', '2021-04-10', 'Replacement Killers, The', 2, 44);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Nulla facilisi.', '2021-03-04', 'Orchestra Rehearsal (Prova d''orchestra)', 2, 36);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Aliquam sit amet diam in magna bibendum imperdiet.', '2021-03-25', 'Gozu (Gokudô kyôfu dai-gekijô: Gozu)', 2, 44);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Etiam justo.', '2021-03-19', 'Hardcore', 2, 42);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Sed sagittis.', '2021-04-27', 'Triangle', 2, 47);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Nam dui.', '2021-04-02', 'Diary of a Hitman', 2, 48);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Mauris sit amet eros.', '2021-03-02', 'Call Her Savage', 2, 47);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('In blandit ultrices enim.', '2021-02-26', 'Ice Age: A Mammoth Christmas', 2, 35);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Aliquam sit amet diam in magna bibendum imperdiet.', '2021-03-08', 'Shorts', 2, 43);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Praesent blandit lacinia erat.', '2021-05-14', 'Bad Luck Love', 2, 38);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Phasellus id sapien in sapien iaculis congue.', '2021-03-03', 'Kin-Dza-Dza!', 2, 46);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Sed accumsan felis.', '2021-03-30', 'Under the Sand', 2, 40);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('In hac habitasse platea dictumst.', '2021-04-24', 'Immensee', 2, 46);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Donec ut dolor.', '2021-03-26', 'Lulu on the Bridge', 2,35);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2021-05-14', 'Brother (Hermano)', 2, 45);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', '2021-03-23', 'Street Kings', 2, 47);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('In blandit ultrices enim.', '2021-03-21', 'Red Shoes, The', 2, 37);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Donec ut mauris eget massa tempor convallis.', '2021-02-12', 'Better Off Dead...', 2, 48);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Praesent id massa id nisl venenatis lacinia.', '2021-04-09', 'Another Country', 2, 43);
-- Coucours 3
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Nulla tempus.', '2018-04-12', 'It Rains in My Village (Bice skoro propast sveta)', 3, 56);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Morbi quis tortor id nulla ultrices aliquet.', '2018-04-27', 'Furry Vengeance', 3, 64);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('In hac habitasse platea dictumst.', '2018-06-02', 'Colt Comrades', 3, 54);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Cras pellentesque volutpat dui.', '2018-06-21', 'Ballast', 3, 50);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Donec dapibus.', '2018-05-07', 'King & Country', 3, 52);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Vestibulum rutrum rutrum neque.', '2018-05-27', 'Kumail Nanjiani: Beta Male ', 3, 59);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Morbi ut odio.', '2018-05-01', 'Green Light', 3, 62);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Donec ut dolor.', '2018-05-23', 'Deal, The', 3, 53);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Duis aliquam convallis nunc.', '2018-06-22', 'Death of a Bureaucrat (La muerte de un burócrata)', 3, 60);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Maecenas ut massa quis augue luctus tincidunt.', '2018-05-31', 'Casino', 3, 62);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Praesent blandit.', '2018-06-19', 'Joe the King', 3, 64);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('In eleifend quam a odio.', '2018-04-14', 'Chipmunk Adventure, The', 3, 63);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Aliquam non mauris.', '2018-06-07', 'Deciduous Tree (Tree Without Leaves) (Rakuyôju)', 3, 56);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Integer tincidunt ante vel ipsum.', '2018-04-14', 'Jesus Christ Superstar', 3, 63);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('In congue.', '2018-04-19', 'Intruder, The (L''intrus)', 3, 61);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Aenean lectus.', '2018-05-02', 'Enforcer, The (Gei ba ba de xin)', 3, 61);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Aliquam erat volutpat.', '2018-04-27', 'Secret Life of Walter Mitty, The', 3, 51);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Curabitur gravida nisi at nibh.', '2018-05-24', 'Once in the Life', 3, 51);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Fusce consequat.', '2018-04-14', 'Departed, The', 3, 50);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Nullam molestie nibh in lectus.', '2018-04-12', 'Metropolis', 3, 54);
-- Concours 4
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Etiam pretium iaculis justo.', '2017-06-29', 'Blood: The Last Vampire', 4, 77);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', '2017-08-17', 'Chimes at Midnight (Campanadas a medianoche)', 4, 76);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Nulla ut erat id mauris vulputate elementum.', '2017-08-16', 'Last Circus, The (Balada triste de trompeta) (Sad Trumpet Ballad, A)', 4, 65);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Nam tristique tortor eu pede.', '2017-07-13', 'Opera', 4, 71);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Duis at velit eu est congue elementum.', '2017-08-21', 'Heldorado', 4, 72);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Nullam varius.', '2017-06-16', 'Mogambo', 4, 72);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Nam nulla.', '2017-07-09', 'Gendarme Gets Married, The (Le gendarme se marie)', 4, 67);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Maecenas ut massa quis augue luctus tincidunt.', '2017-09-08', 'House of 9', 4, 77);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Ut tellus.', '2017-08-18', 'Last Hurrah for Chivalry (Hao xia)', 4, 69);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Quisque ut erat.', '2017-09-08', 'City Slacker', 4, 68);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Aliquam erat volutpat.', '2017-07-09', 'Evil That Men Do, The', 4, 75);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Nunc rhoncus dui vel sem.', '2017-08-08', 'The Blood of Fu Manchu', 4, 76);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '2017-09-04', 'The Stranger''s Return', 4, 66);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', '2017-06-19', 'Who Wants to Kill Jessie? (Kdo chce zabít Jessii?)', 4, 78);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Etiam faucibus cursus urna.', '2017-06-23', 'California Solo', 4, 78);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', '2017-08-03', 'Hardware', 4, 79);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('In hac habitasse platea dictumst.', '2017-07-26', 'Life After Beth', 4, 67);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Praesent id massa id nisl venenatis lacinia.', '2017-08-17', 'Faraway, So Close (In weiter Ferne, so nah!)', 4, 66);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('In quis justo.', '2017-08-19', 'Death Before Dishonor', 4, 79);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Duis at velit eu est congue elementum.', '2017-06-28', 'Secret Life of Words, The', 4, 71);
-- Concours 5
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Morbi non lectus.', '2016-10-16', 'Way South, The (De weg naar het zuiden)', 5, 81);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('In blandit ultrices enim.', '2016-12-06', 'Two Years at Sea', 5, 93);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Donec ut dolor.', '2016-12-12', 'Parisian Love', 5, 89);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '2016-11-14', 'Cherish', 5, 91);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Quisque porta volutpat erat.', '2016-11-28', 'Nibelungen: Kriemhild''s Revenge, Die (Die Nibelungen: Kriemhilds Rache)', 5, 88);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Morbi porttitor lorem id ligula.', '2016-12-06', 'Teheran 43: Spy Ring (a.k.a. Assassination Attempt) (Tegeran-43)', 5, 89);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Integer ac neque.', '2016-12-15', 'Storage', 5, 90);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2016-10-16', 'Guns of Navarone, The', 5, 80);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Nullam varius.', '2016-11-17', 'Dead Zone, The', 5, 84);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Aliquam erat volutpat.', '2016-11-12', 'World War Z', 5, 91);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Etiam justo.', '2016-11-26', 'Beeswax', 5, 84);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Integer tincidunt ante vel ipsum.', '2016-11-18', 'Let the Fire Burn', 5, 92);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Proin eu mi.', '2016-10-29', 'Vice Squad', 5, 92);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Integer a nibh.', '2016-12-06', 'Portrait in Black', 5, 86);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Donec quis orci eget orci vehicula condimentum.', '2016-12-15', 'Voyage to the Bottom of the Sea', 5, 87);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Proin eu mi.', '2016-11-23', '16 Acres', 5, 93);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', '2016-11-10', 'Airplane!', 5, 83);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Nulla tempus.', '2016-12-15', 'Stolen Kisses (Baisers volés)', 5, 87);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Aenean auctor gravida sem.', '2016-12-02', 'Dragonquest', 5, 85);
insert into DESSIN (commentaire, dateRemise, leDessin, numConcours, numCompetiteur) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', '2016-11-30', 'Chained for Life', 5, 80);