insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Coggen', 'Genevra', 43, '4357 Birchwood Place', 'gcoggen0', '3RdBMQ', 5, '2016-03-12');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Raycroft', 'Suzanna', 65, '3 Golf Course Lane', 'sraycroft1', 'BCnZFup', 5, '2017-08-24');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Wawer', 'Lucho', 93, '22 Red Cloud Place', 'lwawer2', 'SCJj7VnP0gy', 5, '2020-07-25');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Rosenshine', 'Fields', 100, '92614 5th Parkway', 'frosenshine3', 'VILRSaDYa9Zp', 2, '2010-02-28');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Sprionghall', 'Adena', 71, '7 5th Drive', 'asprionghall4', 'jxyMNW7ZrP', 3, '2014-12-25');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Drogan', 'Rorke', 34, '2 Anhalt Way', 'rdrogan5', 'E7cJ06ez', 4, '2021-03-03');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Blackmore', 'Carney', 36, '64931 Iowa Avenue', 'cblackmore6', 'LeI5wA', 1, '2017-12-24');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Legrave', 'Stace', 48, '32563 Fair Oaks Street', 'slegrave7', 'vK7y4ibx0nS', 1, '2014-01-14');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Thornborrow', 'Shane', 39, '72 Huxley Circle', 'sthornborrow8', 'IvICZfT', 5, '2014-02-06');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Roderham', 'Vick', 36, '508 Grover Avenue', 'vroderham9', '86Klev', 3, '2012-12-07');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Seman', 'Clarke', 33, '5684 Linden Trail', 'csemana', 'X6pEhKC7V3', 3, '2019-05-31');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Leggate', 'Bing', 46, '2822 Straubel Point', 'bleggateb', 's2JyqRm', 5, '2020-11-03');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Coey', 'Galven', 40, '268 Lillian Park', 'gcoeyc', 'AQh8ohTl', 4, '2013-12-05');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Truter', 'Rafaelita', 92, '304 Dexter Junction', 'rtruterd', 'I8P7KRrIdE', 2, '2015-07-20');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Hardy-Piggin', 'Cecelia', 52, '0 Mayfield Place', 'chardypiggine', 'hYldaU', 3, '2021-05-15');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Jotcham', 'Kerk', 64, '0189 Burrows Junction', 'kjotchamf', 'tXiOG9Mq', 3, '2014-08-02');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Laming', 'Aguie', 100, '14793 Farwell Pass', 'alamingg', 'D8FjclfUh', 4, '2010-04-01');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Lars', 'Penelopa', 47, '02 Longview Pass', 'plarsh', 'egrW5vkyu3TM', 2, '2013-04-12');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Gotter', 'Brod', 100, '614 Mayer Lane', 'bgotteri', 'jWGa1e8Zi', 2, '2021-01-18');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Matis', 'Luella', 57, '843 Lunder Park', 'lmatisj', 'UXaSRL', 1, '2021-04-03');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Himsworth', 'Ferdinand', 79, '77 Schiller Place', 'fhimsworthk', '5kqlgjuZAYff', 4, '2022-02-22');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Scherme', 'Hazlett', 43, '4588 Kropf Way', 'hschermel', 'VWawjrMI', 1, '2013-04-13');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Rowley', 'Kattie', 20, '7 Farwell Lane', 'krowleym', '5f7Mmc3xD5c', 1, '2017-01-20');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Coalbran', 'Barn', 97, '104 Buell Court', 'bcoalbrann', 'wFFiBMa', 3, '2020-03-23');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Colleton', 'Erin', 36, '258 Mesta Point', 'ecolletono', 'al3xi8MQ', 4, '2022-12-02');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Hunting', 'Orion', 43, '858 Northwestern Hill', 'ohuntingp', 'tZW7i9ecuUN', 2, '2011-03-01');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Brantl', 'Alida', 27, '25882 Logan Circle', 'abrantlq', 'BisRo7IAv', 1, '2010-06-25');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Leman', 'Gannie', 51, '8185 Delaware Lane', 'glemanr', 'lz6kuez7L', 5, '2015-06-22');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Nizard', 'Karola', 70, '57410 Bultman Point', 'knizards', 'G9WBOG8xMZ', 2, '2014-09-20');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Bwye', 'Carmelle', 97, '054 Rusk Point', 'cbwyet', 'kmizss', 3, '2012-01-08');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Craster', 'Erna', 71, '1299 Karstens Plaza', 'ecrasteru', '5JudkvEL', 2, '2022-01-01');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Mc Harg', 'Carmelia', 60, '3 Thackeray Avenue', 'cmchargv', 'O2igQPr2', 5, '2022-03-24');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Kleisle', 'Janet', 19, '969 Pawling Place', 'jkleislew', 'hUvVyvvJdXIj', 4, '2021-08-15');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Genicke', 'Brocky', 39, '6114 Golden Leaf Lane', 'bgenickex', 'hJWw8xc', 5, '2022-01-30');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Chidley', 'Cyb', 29, '99 Straubel Point', 'cchidleyy', 'EP2E7t', 5, '2020-09-25');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Tchir', 'Danica', 100, '0759 Scoville Alley', 'dtchirz', 'NV1DCrGdM', 4, '2021-12-24');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Coakley', 'Courtnay', 93, '50599 Di Loreto Way', 'ccoakley10', 'iqGH8j', 2, '2019-03-02');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Best', 'Chrysa', 20, '14575 Oak Center', 'cbest11', 'YmVySkFqInKc', 1, '2014-07-29');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Pigney', 'Ozzy', 58, '94 Forest Dale Terrace', 'opigney12', 'xQ19gFQ', 3, '2020-09-28');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Alywin', 'Tris', 53, '9 Claremont Street', 'talywin13', 'x0Ygcp', 1, '2015-07-07');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Arnet', 'Van', 96, '0631 Dahle Hill', 'varnet14', 'j7vEmA', 3, '2018-06-10');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Levings', 'Krystyna', 58, '24 Eliot Crossing', 'klevings15', 'ZPyjYImC1', 4, '2013-08-12');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Clampin', 'Hamil', 96, '8457 Mifflin Crossing', 'hclampin16', 'aVqZ0BMwWLj', 3, '2013-02-10');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Cowton', 'Bentley', 56, '06 Lotheville Trail', 'bcowton17', 'r0xLFUnnMck', 4, '2010-07-29');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Fetterplace', 'Alvin', 24, '39442 Sage Trail', 'afetterplace18', 'zVgPJp', 4, '2010-01-27');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Tawse', 'Angie', 88, '286 Meadow Ridge Lane', 'atawse19', 'fMYgz6WUZtG', 1, '2021-04-27');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Broadway', 'Mohandas', 87, '6 Roxbury Street', 'mbroadway1a', 'IEjo1X74M', 1, '2019-07-12');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Bosomworth', 'Law', 62, '5228 Hintze Street', 'lbosomworth1b', 'WVtrGymi', 1, '2022-09-26');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Wehnerr', 'Damon', 70, '7 Forest Hill', 'dwehnerr1c', 'ChKdeEkjycm', 3, '2018-07-20');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Langer', 'Mela', 27, '072 Butterfield Park', 'mlanger1d', 'mzAIepSrnbD6', 4, '2013-03-19');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Seabon', 'Aimee', 65, '0279 Morning Lane', 'aseabon1e', '6sF8Oxpm', 4, '2019-03-25');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Bohlsen', 'Otha', 77, '40 Memorial Terrace', 'obohlsen1f', 'Jd2nSZ', 3, '2010-12-10');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Guwer', 'Denni', 64, '35 Holy Cross Avenue', 'dguwer1g', '2wEi2XVDTX', 2, '2015-03-31');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Barnett', 'Ginelle', 18, '2749 Everett Court', 'gbarnett1h', 'VkCmJX6', 4, '2018-12-12');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Scaysbrook', 'Dulci', 92, '6 Bayside Drive', 'dscaysbrook1i', 'CH1utv', 2, '2021-07-16');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Piwell', 'Say', 61, '52 Warbler Circle', 'spiwell1j', 'PuB6FkT', 4, '2011-05-04');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Wynne', 'Candis', 52, '3383 Declaration Parkway', 'cwynne1k', 'LsOZkD', 5, '2018-10-11');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Ludlom', 'Carlynn', 82, '18 Spenser Avenue', 'cludlom1l', 'VZKBeeDHd2vV', 3, '2017-05-17');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Tilliard', 'Nedda', 50, '3165 Eagle Crest Terrace', 'ntilliard1m', 'iNDcjf0', 1, '2021-01-31');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Matasov', 'Nert', 57, '48 Arkansas Court', 'nmatasov1n', 'ah7LyhZriq9r', 2, '2014-01-27');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Powdrell', 'Brandtr', 98, '4731 Loeprich Drive', 'bpowdrell1o', 'UDWp8U', 3, '2011-11-13');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Melloy', 'Cedric', 60, '17 Everett Trail', 'cmelloy1p', 'XKgpfZRL4', 2, '2018-09-19');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Gianulli', 'Tadio', 26, '18 Clove Pass', 'tgianulli1q', 'NLJnP0W', 2, '2014-02-05');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Dickons', 'Elihu', 40, '0 Oxford Crossing', 'edickons1r', 'vpa7Brpz', 5, '2010-11-20');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Goodspeed', 'Donelle', 87, '98273 Blackbird Crossing', 'dgoodspeed1s', 'qip9tMxtcfV', 3, '2013-06-02');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Castelot', 'Emilie', 67, '92041 Dapin Terrace', 'ecastelot1t', '1SsJ2vhQRDy', 3, '2020-06-04');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Grayley', 'Kameko', 22, '043 Derek Road', 'kgrayley1u', 'q0fmwt', 5, '2011-01-31');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('MacGill', 'Emmalynn', 44, '13342 Carioca Circle', 'emacgill1v', '0YrLrPXL', 5, '2014-01-31');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Simkovitz', 'Fedora', 69, '25794 Veith Terrace', 'fsimkovitz1w', 'pOKfnWCE', 1, '2016-07-24');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('de Bullion', 'Fawn', 49, '0060 Fair Oaks Terrace', 'fdebullion1x', 'fmM7fXm', 3, '2021-06-08');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Jereatt', 'Allyson', 77, '4 6th Crossing', 'ajereatt1y', '0nqT0SNhW', 1, '2013-07-18');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Hargrove', 'Lila', 47, '90764 Hintze Road', 'lhargrove1z', 'HxKto4YS7i', 2, '2019-02-11');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Brickell', 'Lyndsie', 82, '1174 Debra Alley', 'lbrickell20', 'Or210u', 3, '2017-07-07');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Gorden', 'Korie', 18, '9 Bartelt Center', 'kgorden21', 'G0JAcwqhfz88', 2, '2015-07-21');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Wakley', 'Sutherland', 24, '9 Anthes Circle', 'swakley22', '0SWPykyZL', 3, '2015-07-12');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Dougan', 'Llywellyn', 65, '48188 Comanche Park', 'ldougan23', 'gyg9YM', 3, '2011-06-29');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Jarrett', 'Ezri', 43, '063 Laurel Drive', 'ejarrett24', 'LvTQHIYeAvjF', 3, '2011-09-22');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Oppie', 'Giustina', 88, '7 Buell Way', 'goppie25', 'ZkCL5w0hoF45', 5, '2010-12-07');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Garms', 'Chelsey', 77, '062 Havey Alley', 'cgarms26', 'Ed31VPi', 2, '2021-03-27');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Varvell', 'Nissy', 55, '55 Shelley Junction', 'nvarvell27', 'cRBoKhHvF', 3, '2013-02-01');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Grent', 'Boonie', 80, '60470 Oak Hill', 'bgrent28', 'kc8qtyJ1cN', 4, '2010-08-23');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Wentworth', 'Che', 33, '8568 Onsgard Center', 'cwentworth29', '8mCOdtOg1M', 5, '2015-10-02');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Buggs', 'Aurlie', 94, '82 Hovde Pass', 'abuggs2a', 'iYhdgjlseS', 2, '2017-03-16');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Lishmund', 'Teddie', 84, '7 Cherokee Terrace', 'tlishmund2b', 'ma4RIdT', 5, '2017-08-10');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Humphries', 'Row', 41, '048 Caliangt Trail', 'rhumphries2c', 'aAzvXv7yvme', 4, '2014-05-22');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Catlette', 'Griffie', 24, '94 Pennsylvania Circle', 'gcatlette2d', 'rQAgmWUS', 1, '2013-08-07');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Pennock', 'Hamilton', 56, '39261 Ohio Parkway', 'hpennock2e', 'zT2igsJmZ0', 4, '2017-11-02');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Marvin', 'Baryram', 44, '426 Rieder Parkway', 'bmarvin2f', 'Lh8w4Zm', 2, '2017-12-19');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Dunnett', 'Judi', 49, '52 Graedel Avenue', 'jdunnett2g', 'FYLMs3tWpV', 3, '2013-07-08');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Ennever', 'Barnabe', 44, '13500 Kedzie Crossing', 'bennever2h', 'UH3D0lEDyV', 2, '2022-11-19');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Phillpot', 'Jeno', 34, '81331 Pond Park', 'jphillpot2i', 'nEvSJm4B', 1, '2012-02-27');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Athelstan', 'Dickie', 21, '81 Sachs Circle', 'dathelstan2j', 'hhRQ6Q', 1, '2012-03-23');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Skeldon', 'Brander', 84, '819 Eagan Way', 'bskeldon2k', 'S0ZCM99D0Ox', 1, '2016-08-05');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Cowan', 'Edee', 26, '75 Buena Vista Street', 'ecowan2l', 'wRu3K1hz0hSC', 3, '2013-08-03');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Gillanders', 'Nealy', 42, '25087 Vermont Way', 'ngillanders2m', 'pbOx3iw81', 2, '2022-03-26');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('McCafferky', 'Logan', 46, '635 Fuller Place', 'lmccafferky2n', 'OcH8RlWwU', 2, '2015-12-12');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Trenholme', 'Tansy', 18, '2120 Kingsford Court', 'ttrenholme2o', 'l1brgEaVFO', 1, '2021-06-15');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('D''Acth', 'Hussein', 26, '0952 Duke Plaza', 'hdacth2p', 'q0QpNBZ', 2, '2019-06-24');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('McMeekan', 'Gertie', 73, '5706 1st Crossing', 'gmcmeekan2q', 'o0QMwQc6s7V', 1, '2021-08-31');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Sherebrooke', 'Kimmi', 89, '64632 Toban Drive', 'ksherebrooke2r', '468kR2', 4, '2010-01-10');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Olensby', 'Hank', 55, '18 Loomis Avenue', 'holensby2s', 'wcsW1sDv', 3, '2017-05-06');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Gallier', 'Donal', 38, '012 Oneill Park', 'dgallier2t', 'gfaek9Y', 5, '2020-12-07');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Marrows', 'Ainsley', 100, '78 Ilene Way', 'amarrows2u', 'WSbxXV6', 1, '2014-06-02');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Kidd', 'Onida', 78, '35 Nancy Drive', 'okidd2v', 'hp6gi7QmM5i', 5, '2016-05-09');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Harcombe', 'Trescha', 39, '90 Riverside Trail', 'tharcombe2w', 'Ofe2Dt', 3, '2011-05-09');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Passion', 'Tildi', 99, '620 Dottie Road', 'tpassion2x', 'I1M4lPVNW5', 2, '2013-09-29');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Wigmore', 'Barth', 48, '68 Claremont Park', 'bwigmore2y', 'ca84n2XdFv', 2, '2019-12-28');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Mallya', 'Raddie', 28, '42268 Nelson Avenue', 'rmallya2z', 'mQGbhYVhOU9T', 1, '2014-10-24');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Solomonides', 'Justinian', 24, '37759 Oxford Place', 'jsolomonides30', 'Bi9umN', 5, '2014-12-15');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Ruoff', 'Riannon', 85, '32 Green Ridge Trail', 'rruoff31', 'PRWAo1', 4, '2019-03-15');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Brudenell', 'Moreen', 83, '2169 Bayside Drive', 'mbrudenell32', 'EJdo1qyv2sL', 5, '2013-12-19');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Ingon', 'Gloria', 36, '6442 Prairie Rose Trail', 'gingon33', '3S6W4vQfiz7', 1, '2019-07-28');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Balnaves', 'Daisey', 50, '4435 Warbler Avenue', 'dbalnaves34', 'GUWLpC', 1, '2013-11-13');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Spowart', 'Moselle', 44, '55 Westend Point', 'mspowart35', 'KW2FfE', 2, '2013-01-23');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Guidelli', 'Calypso', 21, '69400 Armistice Crossing', 'cguidelli36', 'VEKtLkn', 5, '2019-10-04');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Dormon', 'Dalis', 40, '47 Jenifer Avenue', 'ddormon37', '2AukNdgk1Ct', 5, '2019-12-04');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Bradtke', 'Ash', 86, '4 Jenifer Road', 'abradtke38', 'i2lb69G', 5, '2014-07-20');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Bonnette', 'Flore', 34, '73 American Avenue', 'fbonnette39', 'jxMQ7h', 5, '2018-07-09');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Zupo', 'Aubry', 40, '06404 Meadow Vale Point', 'azupo3a', '2GRxmlfgn1T', 1, '2020-05-05');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Pods', 'Kira', 19, '33888 Rusk Circle', 'kpods3b', 'mx5luZm8LuUQ', 5, '2018-08-12');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Cud', 'Hillary', 91, '54954 Laurel Pass', 'hcud3c', 'IqrVAIX', 5, '2012-07-06');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Janusik', 'Nelly', 94, '9 Anzinger Way', 'njanusik3d', 'LpWGzk', 1, '2018-07-28');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Lehrmann', 'Moira', 87, '52728 Summerview Junction', 'mlehrmann3e', '2BnGslfCgNbO', 5, '2010-01-21');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Gregg', 'Quintana', 28, '645 Division Place', 'qgregg3f', 'ekNqrp4n', 1, '2015-12-17');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Sitwell', 'Georgie', 86, '38456 Melrose Road', 'gsitwell3g', '0bCafL', 1, '2016-07-09');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Barensen', 'Tansy', 98, '3 Myrtle Avenue', 'tbarensen3h', '2BX6th9Tv', 2, '2012-07-25');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Hatherall', 'Geraldine', 50, '984 Carpenter Crossing', 'ghatherall3i', 'PCQAJSfkD', 2, '2021-09-11');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Oblein', 'Engracia', 78, '780 Glacier Hill Center', 'eoblein3j', '2kzlRk59uT57', 4, '2019-10-30');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Smelley', 'Yetta', 60, '1664 Elmside Circle', 'ysmelley3k', 'wwzCHjyYKb', 3, '2014-03-17');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Howett', 'Kit', 65, '316 Warbler Circle', 'khowett3l', 'jgcXEIsfb', 5, '2012-12-23');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Duny', 'Anne-marie', 70, '0 Miller Parkway', 'aduny3m', 'RVZk8F', 1, '2020-05-15');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Falkinder', 'Lem', 46, '8 Crowley Center', 'lfalkinder3n', 'kasaMVU1vU2C', 4, '2020-07-07');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Middis', 'Hiram', 59, '09917 Maryland Way', 'hmiddis3o', 'Q66X2Lo6v', 3, '2022-10-12');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Rawles', 'Maisie', 38, '75 Nancy Road', 'mrawles3p', 'Hc9JMOnM4L', 5, '2012-08-10');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Flude', 'Kristan', 93, '77 Hoffman Center', 'kflude3q', 'X6X7xA52k6bh', 3, '2018-02-17');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Carlan', 'Pall', 58, '9435 Maple Wood Place', 'pcarlan3r', 'n3mMKK', 4, '2011-03-07');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Beaves', 'Bar', 51, '24711 Dexter Road', 'bbeaves3s', 'laf6I8UyP', 1, '2014-06-19');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Gillani', 'Hewitt', 41, '97 Arapahoe Park', 'hgillani3t', 'kKEi37O7G', 5, '2017-11-15');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Semarke', 'Franzen', 81, '70889 Dakota Court', 'fsemarke3u', 'pNLtk39', 3, '2017-06-15');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Tills', 'Cobbie', 26, '7 Moose Hill', 'ctills3v', 'MQxS0PI3', 2, '2017-01-09');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Macknish', 'Carlin', 59, '44 Walton Court', 'cmacknish3w', 'tqgMXaNBk', 2, '2017-04-22');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Polon', 'Enos', 90, '0 Norway Maple Court', 'epolon3x', 't0cq0rK7vzK', 4, '2012-01-15');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('de Clerc', 'Leilah', 87, '5252 Schiller Point', 'ldeclerc3y', 'LR44b6gKTY', 3, '2021-12-02');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Macy', 'Laurence', 81, '79240 Prairie Rose Parkway', 'lmacy3z', 'FRYvPOp', 2, '2013-01-11');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Reith', 'Pearle', 63, '3933 Kedzie Street', 'preith40', 'meitbF', 4, '2019-01-24');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Alecock', 'Tamera', 39, '6316 Havey Terrace', 'talecock41', 'dFenv2Y5Ndd', 5, '2015-05-02');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Orta', 'Gordy', 88, '84 Sage Place', 'gorta42', 'NudKf9DOuP', 5, '2012-07-04');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Brosini', 'Bentlee', 73, '297 Pleasure Place', 'bbrosini43', '6A02X3CK', 1, '2021-08-02');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Blethyn', 'Fae', 86, '48197 Manitowish Crossing', 'fblethyn44', 'MpolnDU6h', 3, '2017-01-25');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Boggon', 'Aurea', 40, '3 Hanover Parkway', 'aboggon45', 'hD8HIhSbDT', 1, '2021-08-30');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Deboy', 'Linda', 36, '74 Gale Way', 'ldeboy46', '0OgjY5', 1, '2014-10-28');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Beers', 'Etheline', 92, '95 Shopko Plaza', 'ebeers47', 'MwCOAtU', 4, '2015-02-24');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Poyle', 'Israel', 98, '54 Montana Road', 'ipoyle48', 'DjELCd', 2, '2012-09-07');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Melior', 'Natale', 65, '60642 Del Sol Trail', 'nmelior49', 's49yKkNG0K14', 3, '2011-10-23');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Vanyukhin', 'Dougie', 50, '019 Hudson Point', 'dvanyukhin4a', 'jbOmCnYqB', 2, '2020-08-20');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Rodenborch', 'Lorilyn', 86, '58 Dixon Trail', 'lrodenborch4b', 'tVE2qvYTBU', 4, '2019-09-20');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Batiste', 'Feodora', 61, '72 Banding Trail', 'fbatiste4c', '2755VnLF8qN', 2, '2021-06-07');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Aldwinckle', 'Van', 90, '065 Clove Crossing', 'valdwinckle4d', 'lnPV4StNcCN', 2, '2019-08-14');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Kewley', 'Deny', 44, '07 Dawn Avenue', 'dkewley4e', 'WBil7X', 3, '2022-02-28');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Yesinov', 'Riva', 88, '2 Miller Alley', 'ryesinov4f', 'BmsL8Mz', 4, '2015-03-26');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Gras', 'Humfrey', 100, '5621 Susan Avenue', 'hgras4g', 'yjaW9WwMvd', 3, '2019-06-03');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Skurray', 'Amby', 92, '88 Columbus Alley', 'askurray4h', 'uEzEbfRaouCU', 5, '2013-07-24');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Castles', 'Zechariah', 23, '6 Kingsford Circle', 'zcastles4i', '4QeGBE3vOY', 2, '2018-10-29');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Gerritzen', 'Rosalinde', 46, '564 Crowley Circle', 'rgerritzen4j', 'PGUQTK7kgEFR', 3, '2019-05-21');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Ply', 'Thane', 87, '3164 Goodland Parkway', 'tply4k', '5rxKG409XbH', 2, '2020-01-22');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Benninck', 'Rasla', 42, '9090 Oxford Hill', 'rbenninck4l', 'mm8vcJaM', 4, '2014-03-11');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Selwyn', 'Sascha', 21, '6980 Schurz Street', 'sselwyn4m', 'c9dvK1y', 3, '2022-03-12');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Legan', 'Sukey', 90, '86 Arrowood Drive', 'slegan4n', '38DjzpppOOW2', 5, '2019-01-04');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Kupec', 'Merry', 38, '82 Schmedeman Parkway', 'mkupec4o', 'KhlORZc', 5, '2017-12-09');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Suero', 'Tiphany', 79, '83 Michigan Trail', 'tsuero4p', 'ASTcmO', 4, '2013-10-05');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Dymidowski', 'Paten', 96, '05354 Grover Plaza', 'pdymidowski4q', '20RIpm', 2, '2010-02-21');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Magog', 'Sonja', 18, '9023 Ryan Place', 'smagog4r', 'feUxYkr', 3, '2018-11-06');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('De Francesco', 'Marilee', 68, '663 Magdeline Junction', 'mdefrancesco4s', 'cDFKXHDGhaTX', 4, '2011-07-13');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Dubery', 'Benny', 26, '7417 Buena Vista Parkway', 'bdubery4t', 'coVhkW', 1, '2011-01-22');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Conerding', 'Sharlene', 81, '4388 Daystar Way', 'sconerding4u', 'CjZU5V4K', 5, '2022-04-16');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Jencey', 'Bert', 57, '38242 Butternut Trail', 'bjencey4v', 'dIxYprrtHD', 5, '2010-12-23');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Wellard', 'Giffie', 71, '9 Bartelt Center', 'gwellard4w', 'BIpVJRq', 1, '2019-02-16');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Najafian', 'Nikolai', 85, '841 Cambridge Lane', 'nnajafian4x', 'upnsoeyEm5', 4, '2011-10-18');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Furst', 'Selia', 47, '95962 Ludington Point', 'sfurst4y', 'ZqPuxs', 1, '2022-09-10');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Heiton', 'Atlante', 95, '8729 Elka Place', 'aheiton4z', 'NhwcSbwOeY', 3, '2020-11-17');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Muddicliffe', 'Benita', 76, '46527 Becker Park', 'bmuddicliffe50', 'l26MhQ2JNSr', 4, '2018-02-16');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Sherwyn', 'Minnaminnie', 28, '9305 Forest Run Street', 'msherwyn51', 'hOnEQCRz', 2, '2022-07-21');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Norvill', 'Muriel', 23, '0 Bluejay Point', 'mnorvill52', 'fkXuUCpLgtB', 3, '2012-05-01');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Goady', 'Easter', 96, '60 Jenna Park', 'egoady53', '6KhELCQN', 1, '2020-08-01');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Balden', 'Milissent', 56, '045 Cottonwood Terrace', 'mbalden54', 'k44i33y', 5, '2012-12-11');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Torri', 'Elinor', 100, '955 Anthes Terrace', 'etorri55', 'BPKFGWzbgr', 1, '2013-11-26');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Self', 'Mal', 55, '6163 Division Avenue', 'mself56', '8ApmBzRvl', 4, '2014-11-01');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Chastey', 'Adrianna', 63, '69480 Forest Street', 'achastey57', 'gRN9R7xu', 5, '2019-06-01');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Dormand', 'Jacinda', 33, '91 Dayton Lane', 'jdormand58', 't9MBPTZ', 3, '2016-06-12');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Le Friec', 'Leigh', 94, '4 Boyd Pass', 'llefriec59', 'pIf9FUgT9A', 1, '2010-04-03');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Nono', 'Emmie', 59, '6072 Pierstorff Crossing', 'enono5a', 'cthiNAN3', 4, '2018-05-27');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Lowrey', 'Beau', 18, '25 Corry Parkway', 'blowrey5b', 'TULo58rM', 3, '2011-10-27');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Lesslie', 'Stesha', 45, '1005 Stephen Place', 'slesslie5c', '7I9LkgbOecA', 3, '2022-09-03');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Kier', 'Hunfredo', 47, '986 Oakridge Hill', 'hkier5d', 'fJa8wn', 3, '2015-08-16');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Littley', 'Olympe', 89, '69541 Dawn Alley', 'olittley5e', '5nNYYem', 4, '2015-03-04');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Lorente', 'Kris', 23, '112 Buhler Center', 'klorente5f', 'SbQ8QlHy4by', 3, '2022-04-15');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Emeny', 'Roman', 42, '449 Linden Place', 'remeny5g', 'BpzzojnSf', 3, '2011-07-16');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Rowden', 'Belinda', 68, '7757 Knutson Avenue', 'browden5h', 'kI4XNuUfhZE', 2, '2019-11-25');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Barcke', 'Launce', 48, '13 Sheridan Crossing', 'lbarcke5i', 's7IHauBpKO', 5, '2019-03-20');
insert into UTILISATEUR (nom, prenom, age, adresse, login, motDePasse, numClub, dateInscription) values ('Smaile', 'Joan', 96, '74006 Farmco Court', 'jsmaile5j', 'DuY9HjljZSzZ', 3, '2012-06-08');