insert into CLUB (NomClub, adresse, numTelephone, ville, region, departement) values ('Kreiger Group', '9 Kennedy Drive', '3084791598', 'Female', 'Alsace', 'Moselle');
insert into CLUB (NomClub, adresse, numTelephone, ville, region, departement) values ('Schuppe-Stoltenberg', '702 Cottonwood Center', '2429375405', 'Male', 'Île-de-France', 'Yvelines');
insert into CLUB (NomClub, adresse, numTelephone, ville, region, departement) values ('Lang and Sons', '529 Ramsey Center', '6304835159', 'Female', 'Alsace', 'Meuse');
insert into CLUB (NomClub, adresse, numTelephone, ville, region, departement) values ('Reynolds-Mueller', '2 Northview Point', '6546572182', 'Female', 'Pays de la Loire', 'Loire Atlantique');
insert into CLUB (NomClub, adresse, numTelephone, ville, region, departement) values ('Hauck LLC', '3422 Transport Center', '9542861673', 'Female', 'Île-de-France', 'Paris');
insert into CLUB (NomClub, adresse, numTelephone, ville, region, departement) values ('Brown-Homenick', '66 Arrowood Place', '9566182910', 'Female', 'Pays de la Loire', 'Maine et Loire');
insert into CLUB (NomClub, adresse, numTelephone, ville, region, departement) values ('Rowe-Luettgen', '5057 Del Sol Crossing', '6095125669', 'Female', 'Pays de la Loire', 'Vendée');
insert into CLUB (NomClub, adresse, numTelephone, ville, region, departement) values ('Sipes, Gibson and Hand', '94 Little Fleur Plaza', '2374804782', 'Female', 'Île-de-France', 'Essone');
insert into CLUB (NomClub, adresse, numTelephone, ville, region, departement) values ('Bogisich-Bergnaum', '1683 Oxford Pass', '9004773104', 'Male', 'Île-de-France', 'Seine et Marne');
insert into CLUB (NomClub, adresse, numTelephone, ville, region, departement) values ('Schinner Inc', '9305 Mccormick Avenue', '4835480265', 'Male', 'Île-de-France', 'Val de Marne');
insert into CLUB (NomClub, adresse, numTelephone, ville, region, departement) values ('Roob, Hodkiewicz and Bernhard', '3668 Granby Hill', '1876972986', 'Non-binary', 'Pays de la Loire', 'Mayenne');
insert into CLUB (NomClub, adresse, numTelephone, ville, region, departement) values ('Rogahn-Altenwerth', '28271 Clarendon Crossing', '5678278166', 'Female', 'Centre', 'Cher');
insert into CLUB (NomClub, adresse, numTelephone, ville, region, departement) values ('Runolfsdottir-Schroeder', '19 Prentice Circle', '5526199339', 'Male', 'Auvergne', 'Ardèche');
insert into CLUB (NomClub, adresse, numTelephone, ville, region, departement) values ('Feil-Jacobs', '4 Texas Trail', '5289249612', 'Female', 'Île-de-France', 'Hauts de Seine');
insert into CLUB (NomClub, adresse, numTelephone, ville, region, departement) values ('Gottlieb, Mertz and Stanton', '9953 Nova Road', '1927925387', 'Bigender', 'Île-de-France', 'Seine Saint Denis');
insert into CLUB (NomClub, adresse, numTelephone, ville, region, departement) values ('Smitham-Lakin', '30490 Messerschmidt Plaza', '7827593039', 'Female', 'Alsace', 'Haute Marne');
insert into CLUB (NomClub, adresse, numTelephone, ville, region, departement) values ('Cremin-Dare', '9 Mitchell Junction', '6954681364', 'Female', 'Centre', 'Indre');
insert into CLUB (NomClub, adresse, numTelephone, ville, region, departement) values ('Herman, Morar and Okuneva', '3637 Debs Plaza', '9018063455', 'Female', 'Bretagne', 'Finistère');
insert into CLUB (NomClub, adresse, numTelephone, ville, region, departement) values ('Aufderhar LLC', '84 Del Mar Place', '7551097899', 'Female', 'Bretagne', 'Morbihan');
insert into CLUB (NomClub, adresse, numTelephone, ville, region, departement) values ('Cruickshank-Tromp', '643 Acker Terrace', '6908182861', 'Male', 'Auvergne', 'Rhone');