mysql -u sitewebuser -p sitewebpassword sitewebbd < insert_club.sql
mysql -u sitewebuser -p sitewebpassword sitewebbd < insert_utilisateur.sql
mysql -u sitewebuser -p sitewebpassword sitewebbd < insert_president.sql
mysql -u sitewebuser -p sitewebpassword sitewebbd < insert_concours.sql
mysql -u sitewebuser -p sitewebpassword sitewebbd < insert_competiteur.sql
mysql -u sitewebuser -p sitewebpassword sitewebbd < insert_administrateur.sql
mysql -u sitewebuser -p sitewebpassword sitewebbd < insert_directeur.sql
mysql -u sitewebuser -p sitewebpassword sitewebbd < insert_dessin.sql
mysql -u sitewebuser -p sitewebpassword sitewebbd < insert_participe_club.sql
mysql -u sitewebuser -p sitewebpassword sitewebbd < insert_participe_concours.sql
mysql -u sitewebuser -p sitewebpassword sitewebbd < insert_dirige.sql
mysql -u sitewebuser -p sitewebpassword sitewebbd < insert_evaluateur.sql
mysql -u sitewebuser -p sitewebpassword sitewebbd < insert_evaluation.sql