insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Vipe', '2 Dayton Street', '6841651466', 23, 'Ciherang', 'Messerschmidt', '65');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Gabtype', '108 Sunnyside Terrace', '1672386209', 71, 'Obesi', 'American Ash', '165');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Pixope', '88724 Messerschmidt Way', '6302067275', 16, 'Sidi Lamine', 'Browning', '0165');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Eidel', '16465 Anzinger Trail', '1243083896', 86, 'Port Sudan', 'Fairfield', '3');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Voonyx', '587 Weeping Birch Pass', '8532213174', 61, 'Mirkovci', 'Springview', '41');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Oyoba', '3833 Waxwing Pass', '5425195566', 34, 'Cortinhas', 'Monica', '18988');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Voolith', '3 Burning Wood Alley', '6022008912', 18, 'Reggada', 'Elmside', '4724');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Wikido', '7 Sugar Junction', '4641116585', 11, 'Changning', 'Monica', '3642');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Kwideo', '6257 Dayton Lane', '8812521053', 6, 'Jiaozhou', 'Cascade', '85');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Aivee', '83614 Ramsey Center', '7291851414', 25, 'Boncong', 'Bluejay', '061');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Camido', '0 Coleman Center', '1021512807', 74, 'Xinhui', 'Shasta', '76');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Photojam', '69935 Merchant Trail', '1481303270', 38, 'Granada', 'Caliangt', '33');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Roombo', '2700 Shelley Hill', '4405583162', 53, 'Yelets', 'Russell', '5');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Voonix', '6 Reindahl Way', '3793356474', 4, 'Agrelo', 'Union', '71');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Tagcat', '96324 Derek Avenue', '1966032791', 38, 'Mrgavan', 'Vidon', '61');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Muxo', '4923 Fuller Parkway', '9529813442', 36, 'Guzhu', 'Red Cloud', '565');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Wikibox', '2790 Bowman Avenue', '1625234536', 58, 'Kuloy', 'Elgar', '92155');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Zava', '6946 Fremont Alley', '7378662352', 52, 'Laúndos', 'Ramsey', '455');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Realcube', '0 Clemons Way', '4879313828', 95, 'Leijiadian', 'Cody', '151');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Viva', '74562 Bonner Junction', '8158170674', 67, 'Linshanhe', 'Red Cloud', '985');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Riffpath', '1859 Clemons Avenue', '8806101135', 12, 'Petropavlovka', 'Farragut', '68');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Shufflester', '073 Maple Wood Hill', '6753904701', 47, 'Bugang', 'Vermont', '671');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Janyx', '65 Swallow Plaza', '3367457606', 99, 'Shingū', 'Village Green', '5575');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Zava', '2098 Sycamore Street', '7671056612', 46, 'Butajīra', 'Monument', '4218');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Twitterbridge', '54980 Graceland Court', '2734378954', 72, 'Huogezhuang', 'Derek', '51');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Feednation', '4 Hanson Terrace', '3086923177', 11, 'Lianovérgi', 'Comanche', '70950');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Oyonder', '22470 Grasskamp Junction', '9058281921', 99, 'Gangkou', 'Sunfield', '66');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Feedfish', '69 Susan Trail', '1285704353', 84, 'Carvalheira', 'Homewood', '3099');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Rhynyx', '75635 Granby Drive', '8168313604', 54, 'Chikushino-shi', 'Summer Ridge', '5834');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Demizz', '602 Summer Ridge Drive', '2513385158', 35, 'Saguenay', 'Heath', '44');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Thoughtworks', '26767 Mcguire Alley', '1519927610', 93, 'Kuznechnoye', 'Forest', '49650');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Rhybox', '28 Meadow Valley Pass', '6772419795', 25, 'Xinlong', 'Lakewood Gardens', '467');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Zooveo', '87895 2nd Trail', '8864788632', 100, 'Angoram', 'Spenser', '77');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Katz', '6 Dovetail Alley', '5233328915', 96, 'Gaobeijie', 'Duke', '71915');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Gabspot', '596 Center Terrace', '4509613191', 36, 'Avon', 'Roxbury', '6404');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Yata', '2792 Vermont Crossing', '5462359131', 63, 'Třinec', 'Londonderry', '123');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Yacero', '80213 Lyons Junction', '4053540416', 64, 'Kertapura', 'Holmberg', '6');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Plambee', '898 Hansons Alley', '2791093199', 61, 'Kisangani', 'Hintze', '161');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Feedmix', '3 Burrows Terrace', '1569437878', 92, 'Quiriquire', 'Twin Pines', '65');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Vitz', '67 Buell Parkway', '3918567882', 27, 'Zoumaling', 'Schurz', '406');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Linklinks', '531 Heath Parkway', '4908574452', 44, 'Shirokaya Rechka', 'Straubel', '84634');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Fanoodle', '45834 Shasta Alley', '9686929944', 98, 'Třinec', 'Old Shore', '44325');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Zoozzy', '1 Talmadge Court', '7574759821', 40, 'Belang', 'Randy', '86000');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Wordpedia', '389 Maywood Place', '1404415977', 67, 'Oepula', 'Upham', '2');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Photospace', '1564 Main Junction', '4233985663', 81, 'Spiczyn', 'Dottie', '0495');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Tazzy', '96386 Merry Street', '4771508697', 59, 'Eucaliptus', 'Fairfield', '6');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Buzzster', '83 Oriole Road', '8182933092', 48, 'Longquan', 'New Castle', '5');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Browsedrive', '8 Loftsgordon Lane', '2708456173', 1, 'Dayr Sharaf', 'Twin Pines', '64');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Teklist', '4390 Kingsford Plaza', '9686632895', 73, 'Babatngon', 'Cherokee', '7');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Camido', '269 Knutson Plaza', '9191591209', 40, 'Sedkyrkeshch', 'Buena Vista', '38919');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Layo', '7316 Morningstar Crossing', '7424969423', 60, 'Kota Kinabalu', 'Knutson', '611');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Mymm', '46 Oakridge Place', '6838445352', 6, 'Paradyż', 'Merry', '702');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Oyoba', '72 Lukken Crossing', '8922839075', 2, 'Dayangzhou', 'Sloan', '1');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Kwinu', '92 David Hill', '8461212321', 22, 'Shirokaya Rechka', 'Sheridan', '63941');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Janyx', '4 Lillian Plaza', '2737046141', 58, 'Yasynuvata', 'High Crossing', '57726');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Yadel', '6 Doe Crossing Crossing', '2293820172', 56, 'Rzeszów', 'Jay', '62');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Innojam', '2164 Iowa Way', '8897354940', 92, 'Tarutung', 'Melody', '392');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Dabtype', '5 Holy Cross Center', '1445525433', 100, 'Ennery', 'Barnett', '5374');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Devpulse', '4231 2nd Circle', '4408781764', 63, 'Haguimit', 'Hazelcrest', '84');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Skynoodle', '8670 Maple Wood Parkway', '5376618394', 77, 'Progër', 'Kennedy', '83079');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Linkbridge', '7470 Bellgrove Alley', '4589331761', 56, 'Dishnā', 'Morrow', '59067');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Realpoint', '2 Utah Plaza', '1292407377', 60, 'Kenscoff', 'Lakewood', '05');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Skalith', '6 Meadow Vale Place', '5807623467', 40, 'Cimo de Vila', 'Russell', '8766');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Skynoodle', '20 Russell Point', '6421804993', 93, 'Pregonero', '2nd', '7');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Kwinu', '43304 7th Center', '2652049381', 59, 'Pilot Butte', 'Johnson', '3031');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Camimbo', '32339 Moulton Circle', '7886476714', 49, 'Oslo', 'Corscot', '880');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Jabberstorm', '31 Basil Circle', '2963313371', 52, 'Nuevo Emperador', 'Carey', '61');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Blogspan', '01 Sloan Park', '5161104012', 40, 'Capacmarca', 'Sunbrook', '80374');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Ntag', '760 Cordelia Park', '4576366727', 30, 'Luzhou', 'Morrow', '729');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Kamba', '728 Morrow Point', '8618603229', 62, 'Arrifes', 'Dryden', '48');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Quire', '1288 Laurel Place', '4546141586', 41, 'Lisala', 'Dapin', '3696');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Edgetag', '86815 Bayside Point', '4221156385', 51, 'San Juan', 'Tennessee', '57');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Skiptube', '0059 Vidon Terrace', '7539232996', 93, 'Jakartovice', 'Dovetail', '8');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Aibox', '997 Clemons Circle', '4749133916', 48, 'Erada', 'Lawn', '38671');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Youspan', '60 Cody Road', '7068309228', 99, 'Columbus', 'Springview', '62');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Photobean', '7694 Fallview Drive', '2958275530', 75, 'Vanderhoof', 'Comanche', '689');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Mita', '99 Ruskin Pass', '5399480277', 73, 'Yur’yevets', 'Logan', '17374');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Voomm', '799 Kennedy Lane', '5558724387', 60, 'Balas', 'Commercial', '9303');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Babblestorm', '41263 Killdeer Avenue', '1656590152', 19, 'Wakduwa’ Barat', 'Village', '7');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Jaxworks', '91828 Waxwing Way', '6691206372', 47, 'Wonorejo', 'Tomscot', '0');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Edgewire', '8 Lerdahl Place', '2148009656', 9, 'Dallas', 'Russell', '01');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Rooxo', '6 Monument Crossing', '3381355240', 12, 'Changping', 'Comanche', '0');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Divavu', '78 Grim Road', '2833044526', 18, 'Pondaguitan', 'Thompson', '602');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Browsecat', '6362 Main Alley', '6742554400', 66, 'Delok', 'Sloan', '8');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Reallinks', '38541 Russell Junction', '2641052565', 79, 'Gujrāt', 'Arizona', '41');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Skalith', '5868 Bluejay Court', '4475142995', 11, 'Srostki', 'Jenna', '0550');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Edgewire', '1973 Harper Trail', '5222868216', 100, 'Liucheng', 'Dakota', '133');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Dynabox', '2970 Sachtjen Lane', '4731535036', 66, 'Sano', 'Manley', '63');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Meejo', '89 Larry Court', '7362440050', 13, 'Martaban', 'Jenifer', '8');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Cogidoo', '03 Donald Crossing', '1164388761', 72, 'Baghdad', 'Dakota', '0');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Roombo', '1 Redwing Avenue', '6589254162', 41, 'Mirzec', 'Riverside', '78312');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Twitterwire', '44098 Mockingbird Court', '9608720189', 91, 'Poroshkovo', 'Park Meadow', '735');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Vinte', '80 5th Junction', '3389608727', 15, 'Dashu', 'Bunker Hill', '9');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Gabtype', '659 Dorton Plaza', '5415257605', 41, 'Caldas', 'Donald', '5');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Eadel', '32699 Anderson Crossing', '2807469611', 72, 'Leones', 'Barnett', '45292');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Tagcat', '653 Wayridge Crossing', '2867319158', 96, 'La Mohammedia', 'Norway Maple', '97');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Realcube', '2210 Schmedeman Parkway', '4239220322', 34, 'Rokytnice', 'Clarendon', '3');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Dynabox', '4 Mendota Court', '1025316539', 14, 'Panggungasri', 'Pond', '81');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Aimbo', '93 Truax Circle', '4497332751', 4, 'Huadian', 'Westridge', '68351');
insert into CLUB (NomClub, adresse, numTelephone, nombreAdherents, ville, departement, region) values ('Kwideo', '595 Dixon Hill', '5307853894', 71, 'Muang Sam Sip', 'Kings', '02982');