SET FOREIGN_KEY_CHECKS=0; -- to disable them

TRUNCATE TABLE ADMINISTRATEUR;
TRUNCATE TABLE CLUB;
TRUNCATE TABLE COMPETITEUR;
TRUNCATE TABLE CONCOURS;
TRUNCATE TABLE DIRECTEUR;
TRUNCATE TABLE DIRIGE;
TRUNCATE TABLE EVALUATEUR;
TRUNCATE TABLE PARTICIPE_CLUB;
TRUNCATE TABLE PARTICIPE_COMPETITEUR;
TRUNCATE TABLE PRESIDENT;
TRUNCATE TABLE UTILISATEUR;

SET FOREIGN_KEY_CHECKS=1; -- to enable them